### ISSUE TITLE
Audio Problem with crash report

### ISSUE THREAD

**Issue by khuonghoanghuy** [Joalor64GH/Rhythmo-SC#10]
It is just me or this one get bug?, i download a latest build but i can't heard anything?
@Joalor64GH 

and also i report the controls problem i wanna tell:
![image](https://github.com/user-attachments/assets/1af50b6b-4113-4076-b5b3-1977b33c9492)

crash log:
Error #2007: Parameter text must be non-null.
openfl/text/TextField.hx (line 3099)
flixel/text/FlxText.hx (line 632)
options/ControlsSubState.hx (line 103)
flixel/FlxState.hx (line 239)
flixel/FlxState.hx (line 248)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 680)
flixel/FlxGame.hx (line 553)

**Comment by Joalor64** [comment]
for the controls problem, you gotta reset them in the main options menu by pressing R
for the audio problem, are you sure the volume (in the game, not on your computer) isn't at 0?

**Comment by khuonghoanghuy** [comment]
the controls problem is solve but the audio problem is still, i can't even figure out how to adjust them?

**Comment by Joalor64** [comment]
hmm, what build are you on? if it's a debug build, what's the commit id?? (look in Main Menu)

**Comment by khuonghoanghuy** [comment]
the latest one with the id build is `1072c7c`

**Comment by Joalor64** [comment]
hmm, the audio is fine for me
let me see something
do you have that small numberpad on your keyboard?
use the plus and minus there i think??

**Comment by khuonghoanghuy** [comment]
My laptop doesnt have any numberpad

**Comment by Joalor64** [comment]
hmm, what does your keyboard look like then?

**Comment by Joalor64** [comment]
or actually, why can't you hear anything?

**Comment by khuonghoanghuy** [comment]
My laptop can heard but i think that the input is not listen?, like normally like psych engine the engine still able to catch the - and + from my laptop keyboard

**Comment by Joalor64** [comment]
okay i just made a new build
go to the Actions tab to try and see if the issue was fixed

**Comment by khuonghoanghuy** [comment]
I will try on the next day

**Comment by khuonghoanghuy** [comment]
the audio on build with id 8a6d7df is work

**Comment by Joalor64** [comment]
yay :D
