### ISSUE TITLE
need help again

### ISSUE THREAD

**Issue by Joalor64** [Joalor64GH/Rhythmo-SC#7]
@yophlox unless you're busy, can you help me again please?
i'm trying to fix the controls binding menu, but either i get an error, or the game crashes

**Comment by st4rxtw** [comment]
argg I'll mess with it a bit later (unless you fix it by then), currently going through hell with a Cuphead decomp lol

**Comment by Joalor64** [comment]
i have somehow managed to fix it
(i have now redid saving inputs TWICE)

**Comment by st4rxtw** [comment]
:sob:
